__all__ = ()

MAX_PRESENCES_DEFAULT = 0
MAX_USERS_DEFAULT = 250000 # Most already has 500000 by default
MAX_STAGE_CHANNEL_VIDEO_USERS_DEFAULT = 50
MAX_VOICE_CHANNEL_VIDEO_USERS_DEFAULT = 25

NAME_LENGTH_MIN = 2
NAME_LENGTH_MAX = 100


GUILD_STATE_MASK_SOUNDBOARD_SOUNDS_REQUESTED = 1 << 0
