__all__ = (
    'EMOJI_UPDATE_DELETE', 'EMOJI_UPDATE_EDIT', 'EMOJI_UPDATE_CREATE', 'EMOJI_UPDATE_NONE', 'LARGE_GUILD_LIMIT',
    'STICKER_UPDATE_DELETE', 'STICKER_UPDATE_EDIT', 'STICKER_UPDATE_CREATE', 'STICKER_UPDATE_NONE', 'VOICE_STATE_JOIN',
    'VOICE_STATE_LEAVE', 'VOICE_STATE_NONE', 'VOICE_STATE_MOVE', 'VOICE_STATE_UPDATE'
)


MAX_PRESENCES_DEFAULT = 0
MAX_USERS_DEFAULT = 250000 # Most already has 500000 by default
MAX_STAGE_CHANNEL_VIDEO_USERS_DEFAULT = 50
MAX_VOICE_CHANNEL_VIDEO_USERS_DEFAULT = 25

NAME_LENGTH_MIN = 2
NAME_LENGTH_MAX = 100

AFK_TIMEOUT_DEFAULT = 0
AFK_TIMEOUT_OPTIONS = frozenset((0, 60, 300, 900, 1800, 3600),)

DESCRIPTION_LENGTH_MAX = 120

LARGE_GUILD_LIMIT = 250 # can be between 50 and 250


# State flags

GUILD_STATE_MASK_SOUNDBOARD_SOUNDS_CACHED = 1 << 0


# Constants for events

EMOJI_UPDATE_NONE = 0
EMOJI_UPDATE_CREATE = 1
EMOJI_UPDATE_DELETE = 2
EMOJI_UPDATE_EDIT = 3


STICKER_UPDATE_NONE = 0
STICKER_UPDATE_CREATE = 1
STICKER_UPDATE_DELETE = 2
STICKER_UPDATE_EDIT = 3


VOICE_STATE_NONE = 0
VOICE_STATE_JOIN = 1
VOICE_STATE_LEAVE = 2
VOICE_STATE_UPDATE = 3
VOICE_STATE_MOVE = 4
