__all__ = ()

from .compability import AUTO_RELOAD_SUPPORTED, INotifyFlags


AUTO_RELOAD_DELAY = 5.0


if AUTO_RELOAD_SUPPORTED:
    WATCH_MASK_GENERAL = INotifyFlags.CREATE | INotifyFlags.DELETE | INotifyFlags.MODIFY | INotifyFlags.DELETE_SELF
    WATCH_MASK_SELF_DELETE = INotifyFlags.DELETE_SELF
    WATCH_MASK_DELETE = INotifyFlags.DELETE
    WATCH_MASK_CREATE = INotifyFlags.CREATE
    WATCH_MASK_UPDATE = INotifyFlags.MODIFY
else:
    WATCH_MASK_GENERAL = 0
    WATCH_MASK_SELF_DELETE = 0
    WATCH_MASK_DELETE = 0
    WATCH_MASK_CREATE = 0
    WATCH_MASK_UPDATE = 0
