name: Feature Request
description: Request a feature for the library
title: "[Feature request] "
labels: feature request
body:
  - type: input
    attributes:
      label: Summary
      description: >
        Please describe what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ideal Solution
      description: >
        Describe the ideal solution, how the feature could be solved, implemented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case code
      description: >
        A short code snippet for example use case.
      render: python
  - type: textarea
    attributes:
      label: Alternative solutions
      description: >
        Describe alternatives solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context or screenshots about the feature request here.
