__all__ = (
    'ATTACHMENT_REQUEST_ACTION_CREATE', 'ATTACHMENT_REQUEST_ACTION_EDIT', 'ATTACHMENT_REQUEST_FIELD_DESCRIPTION',
    'ATTACHMENT_REQUEST_FIELD_SPOILER', 'ATTACHMENT_REQUEST_MASK_ACTION', 'ATTACHMENT_REQUEST_MASK_FIELDS',
    'ATTACHMENT_REQUEST_MASK_TYPE', 'ATTACHMENT_REQUEST_SHIFT_ACTION', 'ATTACHMENT_REQUEST_SHIFT_FIELDS',
    'ATTACHMENT_REQUEST_SHIFT_TYPE', 'ATTACHMENT_REQUEST_TYPE_REGULAR', 'ATTACHMENT_REQUEST_TYPE_VIDEO',
    'ATTACHMENT_REQUEST_TYPE_VOICE', 'ATTACHMENT_REQUEST_WAVEFORM_OGG_DEFAULT'
)

ATTACHMENT_REQUEST_SHIFT_TYPE = 0
ATTACHMENT_REQUEST_SHIFT_ACTION = 8
ATTACHMENT_REQUEST_SHIFT_FIELDS = 16

ATTACHMENT_REQUEST_MASK_TYPE = 0xff
ATTACHMENT_REQUEST_MASK_ACTION = 0xff
ATTACHMENT_REQUEST_MASK_FIELDS = 0xff

ATTACHMENT_REQUEST_TYPE_REGULAR = 1
ATTACHMENT_REQUEST_TYPE_VOICE = 2
ATTACHMENT_REQUEST_TYPE_VIDEO = 3

ATTACHMENT_REQUEST_ACTION_CREATE = 1
ATTACHMENT_REQUEST_ACTION_EDIT = 2

ATTACHMENT_REQUEST_FIELD_DESCRIPTION = 0
ATTACHMENT_REQUEST_FIELD_SPOILER = 1

ATTACHMENT_REQUEST_WAVEFORM_OGG_DEFAULT = (
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
)
