__all__ = ()

from .parameter import TYPE_IDENTIFIER_BOOL, TYPE_IDENTIFIER_FLOAT, TYPE_IDENTIFIER_INT, TYPE_IDENTIFIER_STR


PARAMETER_NOTE_SIGN_OPTIONAL = '*'

PARAMETER_DEFAULT_PREFIX = 'Default: '

PARAMETER_COLUMN_SEPARATOR = '   '
PARAMETER_MODIFIER_SEPARATOR = ' / '

PARAMETER_TYPE_IDENTIFIER_TO_REPRESENTATION = {
    TYPE_IDENTIFIER_STR: 'TEXT',
    TYPE_IDENTIFIER_INT: 'INTEGER',
    TYPE_IDENTIFIER_FLOAT: 'FLOAT',
    TYPE_IDENTIFIER_BOOL: 'BOOLEAN'
}

BOX_LEFT_TOP = '╭─'
BOX_RIGHT_TOP = '─╮'
BOX_LEFT_BOT = '╰─'
BOX_RIGHT_BOT = '─╯'

BOX_LEFT = '│ '
BOX_RIGHT = ' │'

BOX_TOP = '─'
BOX_BOTTOM = '─'

BOX_TITLE_PARAMETER = ' PARAMETERS '
BOX_TITLE_MODIFIER = ' OPTIONS '
